# Generated by Django 5.2.7 on 2025-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rut',
            field=models.CharField(blank=True, help_text='Chilean tax ID (e.g., 12.345.678-9)', max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='company',
            name='rut_cleaned',
            field=models.CharField(blank=True, db_index=True, help_text='RUT without formatting (e.g., 123456789)', max_length=9, null=True, unique=True, verbose_name='RUT (cleaned)'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['rut_cleaned'], name='companies_rut_cle_bfeff7_idx'),
        ),
    ]
