# Generated by Django 5.2.7 on 2025-10-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='processing_metadata',
            field=models.JSONField(blank=True, help_text='Metadata from processing (transactions created, datasets created, processing time, etc.)', null=True, verbose_name='processing metadata'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
