# Generated by Django 5.2.7 on 2025-11-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_rut_to_company'),
        ('analytics', '0002_dataupload_processing_metadata_dataupload_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsresult',
            name='visible_to_roles',
            field=models.JSONField(blank=True, default=dict, verbose_name='visible to roles'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_schema', models.JSONField(help_text='Column mapping: {in_dt: {source_column: "Fecha venta", dtype: "date", format: "%d-%m-%Y"}}', verbose_name='data schema')),
                ('default_formats', models.JSONField(blank=True, default=dict, help_text='Default formats: {date: "%m/%d/%Y %H:%M", float: {thousands: ".", decimal: ","}}', verbose_name='default formats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.OneToOneField(help_text='Company this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_config', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'verbose_name_plural': 'Company Configurations',
                'db_table': 'analytics_company_config',
            },
        ),
    ]
