# Generated by Django 4.2 on 2025-11-03 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_rut_to_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0003_alter_analyticsresult_visible_to_roles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="celery task ID",
                    ),
                ),
                (
                    "models_to_execute",
                    models.JSONField(
                        default=list,
                        help_text='List of model names: ["transactions", "daily", "weekly", "monthly", ...]',
                        verbose_name="models to execute",
                    ),
                ),
                (
                    "models_completed",
                    models.JSONField(
                        default=list,
                        help_text="List of completed model names",
                        verbose_name="models completed",
                    ),
                ),
                (
                    "current_model",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="current model",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="progress (%)"),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="processing time (seconds)"
                    ),
                ),
                (
                    "last_checkpoint",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="last checkpoint",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="error traceback"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="accounts.company",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="analytics.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "processing_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name: transactions, daily, weekly, monthly, product_daily, etc.",
                        max_length=50,
                        verbose_name="model name",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[("filters", "Filters"), ("attrs", "Attributes")],
                        help_text="filters or attrs",
                        max_length=10,
                        verbose_name="result type",
                    ),
                ),
                ("row_count", models.IntegerField(verbose_name="row count")),
                ("column_count", models.IntegerField(verbose_name="column count")),
                (
                    "columns",
                    models.JSONField(
                        help_text="List of column names", verbose_name="columns"
                    ),
                ),
                (
                    "data_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to parquet/CSV file if stored separately",
                        max_length=500,
                        null=True,
                        verbose_name="data path",
                    ),
                ),
                (
                    "data_preview",
                    models.JSONField(
                        blank=True,
                        help_text="First 10 rows for quick viewing",
                        null=True,
                        verbose_name="data preview",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="execution time (ms)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_results",
                        to="accounts.company",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_results",
                        to="analytics.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "model_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (XLSX)"),
                            ("csv", "CSV"),
                            ("pdf", "PDF Report"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="export format",
                    ),
                ),
                (
                    "models_included",
                    models.JSONField(
                        default=list,
                        help_text="List of model names included in export",
                        verbose_name="models included",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="file path"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "download_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="download URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="celery task ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Download link expiration time",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to="accounts.company",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="analytics.processingjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["company", "status"], name="processing__company_babe66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["upload"], name="processing__upload__4fba84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["celery_task_id"], name="processing__celery__4245d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["created_at"], name="processing__created_7e276e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelresult",
            index=models.Index(
                fields=["company", "job"], name="model_resul_company_ffdbc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelresult",
            index=models.Index(
                fields=["job", "model_name"], name="model_resul_job_id_9dee53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelresult",
            index=models.Index(
                fields=["company", "model_name", "result_type"],
                name="model_resul_company_561bbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelresult",
            index=models.Index(
                fields=["created_at"], name="model_resul_created_62fbe9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelresult",
            unique_together={("job", "model_name", "result_type")},
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(
                fields=["company", "status"], name="data_export_company_a462d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(fields=["job"], name="data_export_job_id_152ff9_idx"),
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(
                fields=["created_at"], name="data_export_created_a07408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(
                fields=["expires_at"], name="data_export_expires_8612f9_idx"
            ),
        ),
    ]
